language: generic # don't install any environment
script:
  - bash ./deploy.sh
env:
  global:
  - APL_LOC_DEPLOY_ID: "8ee404f4-9d01-4d82-8dc7-dcf8a99e2fc0"
  - APL_LOC_ARTIFACT_ID: "dd8d371b-e713-4388-897e-58df81f01a95"
  - APL_STACK_ID: "c2ade82c-1c68-4dd9-89f0-a02716ab65ff"
  - APL_RELEASE_ID: "711951cd-d783-4536-a445-8edf80960b3d"
  - APL_STACK_VERSION_ID: "41d5855d-8ffa-4c12-8e6d-029caca2b487"
  - APL_STACK_COMPONENT_ID: "af62e9d4-2ad1-40d8-aae3-348ad0678c8e"
  - APL_COMPONENT_SERVICE_ID: "ct-deployment"
  - APL_ARTIFACT_NAME: "acme-air"
  - APL_CMD_RELEASE: "v0.2.0"